services:
  server:
    build:
      dockerfile: ./Dockerfile
    container_name: server
    env_file:
      - ./.env
    environment:
      - ENV_SOURCE=env
      - PG_HOST=pg
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_USERNAME=${PG_USERNAME}
      - PORT=2024
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - pg
      - redis
    networks:
      - backend
    ports:
      - "2024:2024"
  
  pg:
    image: postgres:16.2
    container_name: pg
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_USER=${PG_USERNAME}
    networks:
      - backend
    ports:
      - "${PG_PORT}:${PG_PORT}"
    restart: always
  
  redis:
    image: redis:latest
    command: --port ${REDIS_PORT}
    container_name: redis
    env_file:
      - ./.env
    networks:
      - backend
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always

networks:
  backend:
    driver: bridge
